version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.api.server:app --reload --workers 2 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    image: ${APP_IMG}:${APP_TAG}
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - my-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data/
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - my-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  my-network:
    driver: bridge
    external: true