---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hereweare-deployment
  namespace: here-we-are
  labels:
    app: hereweare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hereweare
  template:
    metadata:
      labels:
        app: hereweare
    spec:
      containers:
        - name: hereweare
          image: hereweare:dev
          imagePullPolicy: Never
          command: ["uvicorn"]
          args:
            [
              "app.api.server:app",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
              "--workers",
              "2",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: hereweare-app
  namespace: here-we-are
  labels:
    app: hereweare
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8000
      targetPort: 8000
  selector:
    app: hereweare
