apiVersion: v1
kind: Service
metadata:
        name: hereweare-deployment-service
        labels:
                app: hereweare 
spec:
        type: LoadBalancer
        ports:
                - port: 80
        selector:
                app: hereweare  